import { getImageByKey } from "../getImageKey"

export const clientArray = [
  {
    id: 1,
    clients: { firstName: "Mustermann", lastName: "GmbH" },
    type: {
      title: "SFF",
      typeSubscribe: "",
      subscriptionDuration: "",
      userPlaces: 0,
      paymentProcedure: "",
      generalExpenses: 0,
    },
    responsible: { img: getImageByKey("avatar"), name: "Sheldon" },
    date: "21.10.2023",
    employee: 113,
    user: 147,
    load: 96,
    product: 800000,
    project: [
      {
        leftText: "Projektname goes here",
        new: true,
        projectCompletion: 95,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: true,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
    ],
    // actions: false,
    buttons: {
      list: true,
      light_bulb: true,
      message: false,
      loop: true,
    },
  },
  {
    id: 2,
    clients: { firstName: "Илья", lastName: "Юркин" },
    type: {
      title: "SA",
      typeSubscribe: "STUDIO",
      subscriptionDuration: "12 mounth",
      userPlaces: 200,
      paymentProcedure: "Yearly",
      generalExpenses: 6000,
    },
    responsible: { img: getImageByKey(""), name: "Sheldon" },
    date: "22.11.2023",
    employee: 113,
    user: 147,
    load: 82,
    product: 1500000,
    project: [
      {
        leftText: "Projektname goes here",
        new: true,
        projectCompletion: 95,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: true,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
    ],
    // actions: false,
    buttons: {
      list: true,
      light_bulb: true,
      message: true,
      loop: true,
    },
  },
  {
    id: 3,
    clients: { firstName: "Мария", lastName: "Рассказова" },
    type: {
      title: "SFF",
      typeSubscribe: "STUDIO",
      subscriptionDuration: "10 mounth",
      userPlaces: 180,
      paymentProcedure: "Yearly",
      generalExpenses: 8000,
    },
    responsible: { img: getImageByKey(""), name: "Sheldon" },
    date: "15.10.2023",
    employee: 113,
    user: 147,
    load: 82,
    product: 500000,
    project: [
      {
        leftText: "Projektname goes here",
        new: false,
        projectCompletion: 95,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 22,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 42,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 72,
        icon: getImageByKey("euro_svg"),
      },
    ],
    // actions: true,
    buttons: {
      list: false,
      light_bulb: true,
      message: true,
      loop: true,
    },
  },
  {
    id: 4,
    clients: { firstName: "Максим ", lastName: "Попов" },
    type: {
      title: "SFF",
      typeSubscribe: "STUDIO",
      subscriptionDuration: "10 mounth",
      userPlaces: 180,
      paymentProcedure: "Yearly",
      generalExpenses: 8000,
    },
    responsible: { img: getImageByKey(""), name: "Sheldon" },
    date: "22.10.2024",
    employee: 113,
    user: 147,
    load: 82,
    product: 220000,
    project: [
      {
        leftText: "Projektname goes here",
        new: false,
        projectCompletion: 95,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 22,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 42,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 72,
        icon: getImageByKey("euro_svg"),
      },
    ],
    // actions: true,
    buttons: {
      list: false,
      light_bulb: true,
      message: true,
      loop: true,
    },
  },
  {
    id: 5,
    clients: { firstName: "Антон", lastName: "Сафонов" },
    type: {
      title: "SA",
      typeSubscribe: "STUDIO",
      subscriptionDuration: "10 mounth",
      userPlaces: 180,
      paymentProcedure: "Yearly",
      generalExpenses: 8000,
    },
    responsible: { img: getImageByKey(""), name: "Sheldon" },
    date: "23.10.2024",
    employee: 113,
    user: 147,
    load: 82,
    product: 200000,
    project: [
      {
        leftText: "Projektname goes here",
        new: false,
        projectCompletion: 95,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 22,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 42,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 72,
        icon: getImageByKey("euro_svg"),
      },
    ],
    // actions: true,
    buttons: {
      list: false,
      light_bulb: true,
      message: true,
      loop: true,
    },
  },
  {
    id: 6,
    clients: { firstName: "Мария", lastName: "Решетникова" },
    type: {
      title: "SA",
      typeSubscribe: "STUDIO",
      subscriptionDuration: "10 mounth",
      userPlaces: 180,
      paymentProcedure: "Yearly",
      generalExpenses: 8000,
    },
    responsible: { img: getImageByKey(""), name: "Sheldon" },
    date: "24.10.2024",
    employee: 113,
    user: 147,
    load: 82,
    product: 300000,
    project: [
      {
        leftText: "Projektname goes here",
        new: false,
        projectCompletion: 95,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 22,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 42,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 72,
        icon: getImageByKey("euro_svg"),
      },
    ],
    // actions: true,
    buttons: {
      list: false,
      light_bulb: true,
      message: true,
      loop: true,
    },
  },
  {
    id: 7,
    clients: { firstName: "Мария", lastName: "Решетникова" },
    type: {
      title: "SA",
      typeSubscribe: "STUDIO",
      subscriptionDuration: "10 mounth",
      userPlaces: 180,
      paymentProcedure: "Yearly",
      generalExpenses: 8000,
    },
    responsible: { img: getImageByKey(""), name: "Sheldon" },
    date: "24.10.2024",
    employee: 113,
    user: 147,
    load: 82,
    product: 300000,
    project: [
      {
        leftText: "Projektname goes here",
        new: false,
        projectCompletion: 95,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 22,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 42,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 72,
        icon: getImageByKey("euro_svg"),
      },
    ],
    // actions: true,
    buttons: {
      list: false,
      light_bulb: true,
      message: true,
      loop: true,
    },
  },
  {
    id: 8,
    clients: { firstName: "Мария", lastName: "Решетникова" },
    type: {
      title: "SA",
      typeSubscribe: "STUDIO",
      subscriptionDuration: "10 mounth",
      userPlaces: 180,
      paymentProcedure: "Yearly",
      generalExpenses: 8000,
    },
    responsible: { img: getImageByKey(""), name: "Sheldon" },
    date: "24.10.2024",
    employee: 113,
    user: 147,
    load: 82,
    product: 300000,
    project: [
      {
        leftText: "Projektname goes here",
        new: false,
        projectCompletion: 95,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 22,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 42,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 72,
        icon: getImageByKey("euro_svg"),
      },
    ],
    // actions: true,
    buttons: {
      list: false,
      light_bulb: true,
      message: true,
      loop: true,
    },
  },
  {
    id: 9,
    clients: { firstName: "Мария", lastName: "Решетникова" },
    type: {
      title: "SA",
      typeSubscribe: "STUDIO",
      subscriptionDuration: "10 mounth",
      userPlaces: 180,
      paymentProcedure: "Yearly",
      generalExpenses: 8000,
    },
    responsible: { img: getImageByKey(""), name: "Sheldon" },
    date: "24.10.2024",
    employee: 113,
    user: 147,
    load: 82,
    product: 300000,
    project: [
      {
        leftText: "Projektname goes here",
        new: false,
        projectCompletion: 95,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 22,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 42,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 72,
        icon: getImageByKey("euro_svg"),
      },
    ],
    // actions: true,
    buttons: {
      list: false,
      light_bulb: true,
      message: true,
      loop: true,
    },
  },
  {
    id: 10,
    clients: { firstName: "Мария", lastName: "Решетникова" },
    type: {
      title: "SA",
      typeSubscribe: "STUDIO",
      subscriptionDuration: "10 mounth",
      userPlaces: 180,
      paymentProcedure: "Yearly",
      generalExpenses: 8000,
    },
    responsible: { img: getImageByKey(""), name: "Sheldon" },
    date: "24.10.2024",
    employee: 113,
    user: 147,
    load: 82,
    product: 300000,
    project: [
      {
        leftText: "Projektname goes here",
        new: false,
        projectCompletion: 95,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 22,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 42,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 72,
        icon: getImageByKey("euro_svg"),
      },
    ],
    // actions: true,
    buttons: {
      list: false,
      light_bulb: true,
      message: true,
      loop: true,
    },
  },
  {
    id: 11,
    clients: { firstName: "Мария", lastName: "Решетникова" },
    type: {
      title: "SA",
      typeSubscribe: "STUDIO",
      subscriptionDuration: "10 mounth",
      userPlaces: 180,
      paymentProcedure: "Yearly",
      generalExpenses: 8000,
    },
    responsible: { img: getImageByKey(""), name: "Sheldon" },
    date: "24.10.2024",
    employee: 113,
    user: 147,
    load: 82,
    product: 300000,
    project: [
      {
        leftText: "Projektname goes here",
        new: false,
        projectCompletion: 95,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 22,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 42,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 72,
        icon: getImageByKey("euro_svg"),
      },
    ],
    // actions: true,
    buttons: {
      list: false,
      light_bulb: true,
      message: true,
      loop: true,
    },
  },
  {
    id: 12,
    clients: { firstName: "Мария", lastName: "Решетникова" },
    type: {
      title: "SA",
      typeSubscribe: "STUDIO",
      subscriptionDuration: "10 mounth",
      userPlaces: 180,
      paymentProcedure: "Yearly",
      generalExpenses: 8000,
    },
    responsible: { img: getImageByKey(""), name: "Sheldon" },
    date: "24.10.2024",
    employee: 113,
    user: 147,
    load: 82,
    product: 300000,
    project: [
      {
        leftText: "Projektname goes here",
        new: false,
        projectCompletion: 95,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 82,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 22,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Projektname goes",
        new: false,
        projectCompletion: 42,
        icon: getImageByKey("euro_svg"),
      },
      {
        leftText: "Other project",
        new: false,
        projectCompletion: 72,
        icon: getImageByKey("euro_svg"),
      },
    ],
    // actions: true,
    buttons: {
      list: false,
      light_bulb: true,
      message: true,
      loop: true,
    },
  },
]
